apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
spec:
  type: NodePort
  ports:
    - name: http
      port: 4466
      targetPort: 4466
      nodePort: 30046
  selector:
    app.kubernetes.io/name: headlamp
