apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf2-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 25Gi
