apiVersion: v1
kind: PersistentVolume
metadata:
  name: vintagestory-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /persist/kubernetes/storage/vintagestory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pluto
  claimRef:
    namespace: games
    name: vintagestory-data
