apiVersion: v1
kind: Service
metadata:
  name: vintagestory-service
  namespace: games
  labels:
    app: vintagestory
spec:
  type: ClusterIP
  selector:
    app: vintagestory
  ports:
    - name: game-tcp
      port: 42420
      targetPort: 42420
      protocol: TCP
    - name: game-udp
      port: 42420
      targetPort: 42420
      protocol: UDP
