apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: pluto-cluster
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: jellyfin.apollan.cc
        service: http://jellyfin.media.svc.cluster.local:8096
      - hostname: homeassistant.apollan.cc
        service: http://home-assistant.home-automation.svc.cluster.local:8123
      - hostname: joplin.apollan.cc
        service: http://joplin.productivity.svc.cluster.local:22300
      - hostname: zotero.apollan.cc
        service: http://zotero.productivity.svc.cluster.local:80
      - service: http_status:404
