apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-postgres-data
  namespace: productivity
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
