apiVersion: v1
kind: Service
metadata:
  name: joplin
  namespace: productivity
  labels:
    app: joplin
spec:
  type: ClusterIP
  selector:
    app: joplin
  ports:
    - name: http
      port: 22300
      targetPort: 22300
