apiVersion: v1
kind: Service
metadata:
  name: zotero
  namespace: productivity
  labels:
    app: zotero
spec:
  type: ClusterIP
  selector:
    app: zotero
  ports:
    - name: http
      port: 80
      targetPort: 80
