apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-provisioner
  - local-path-provisioner
  # - longhorn (disabled; all storage is currently local-path and nfs-client)
  - cloudflared
  - cloudflare-ddns
