apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-provisioner
  # Ingress tunnel for web services disabled until web apps (home-assistant/jellyfin) are enabled
  # - cloudflared
