apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minecraft
  - factorio
  - tf2
  # Smart home and media workloads disabled for now
  # - home-assistant
  # - jellyfin
  # - arr
