apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minecraft
  - factorio
  - tf2
  - home-assistant
  - joplin
  - zotero
  # 🛑 Media streaming & downloading stacks disabled until Sol ZFS NAS is online:
  # - jellyfin
  # - arr
