apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /persist/kubernetes/storage/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pluto
  claimRef:
    namespace: games
    name: minecraft-data
